import logo from "../assets/Logo/3.png";
import doctor1 from "../assets/Doctors/1.avif";
import doctor2 from "../assets/Doctors/2.webp";
import heroImg from "../assets/Banner/doctoringrp.png";
import advbanner from "../assets/Banner/1.png";
import speciality1 from "../assets/SpecialityImgs/1.jpg";
import speciality2 from "../assets/SpecialityImgs/2.jpg";
import speciality3 from "../assets/SpecialityImgs/3.jpg";
import speciality4 from "../assets/SpecialityImgs/4.webp";
import speciality5 from "../assets/SpecialityImgs/5.jpg";
import speciality6 from "../assets/SpecialityImgs/6.jpg";

export const images = {
  logo,
  doctors: [doctor1, doctor2],
  hero: heroImg,
  adv: advbanner,
};

export const speciality = [
  { label: "Dermatologist", img: speciality1 },
  { label: "Gynecologist", img: speciality2 },
  { label: "Neurologist", img: speciality3 },
  { label: "General Physician", img: speciality6 },
  { label: "Pediatrician", img: speciality5 },
  { label: "Cardiologist", img: speciality4 },
];

export const AllDoctors = [
  {
    id: 1,
    img: doctor1,
    name: "Dr. Cristina Shrestha",
    specializedIn: "Neurologist",
    status: true,
    rating: 4.5,
    experience: "10 years",
    fee: "1500 NPR",
    bio: "Dr. Cristina Shrestha is a highly experienced neurologist specializing in brain and nerve disorders. She is known for her patient-first approach and accurate diagnosis.",
  },
  {
    id: 2,
    img: doctor2,
    name: "Dr. Manabi Shrestha",
    specializedIn: "Gynecologist",
    status: false,
    rating: 4.2,
    experience: "8 years",
    fee: "1200 NPR",
    bio: "Dr. Manabi Shrestha is a trusted gynecologist providing compassionate care in women’s health, prenatal care, and reproductive health management.",
  },
  {
    id: 3,
    img: doctor1,
    name: "Dr. Ashish Rana",
    specializedIn: "Dermatologist",
    status: true,
    rating: 3.9,
    experience: "6 years",
    fee: "1000 NPR",
    bio: "Dr. Ashish Rana is a dermatologist dedicated to treating skin, hair, and nail disorders, with expertise in both cosmetic and clinical dermatology.",
  },
  {
    id: 4,
    img: doctor2,
    name: "Dr. Kabita Sharma",
    specializedIn: "Cardiologist",
    status: true,
    rating: 4.8,
    experience: "12 years",
    fee: "2000 NPR",
    bio: "Dr. Kabita Sharma is a leading cardiologist specializing in heart health, preventive cardiology, and advanced cardiac treatments.",
  },
  {
    id: 5,
    img: doctor1,
    name: "Dr. Prakash Thapa",
    specializedIn: "General Physician",
    status: true,
    rating: 4.0,
    experience: "7 years",
    fee: "800 NPR",
    bio: "Dr. Prakash Thapa is a general physician with extensive experience in diagnosing and managing common illnesses with a holistic approach.",
  },
  {
    id: 6,
    img: doctor2,
    name: "Dr. Anjali Gurung",
    specializedIn: "Pediatrician",
    status: false,
    rating: 4.3,
    experience: "9 years",
    fee: "1100 NPR",
    bio: "Dr. Anjali Gurung is a pediatrician who has been caring for children’s health and development with expertise in preventive and neonatal care.",
  },
  {
    id: 7,
    img: doctor1,
    name: "Dr. Suman Koirala",
    specializedIn: "Cardiologist",
    status: true,
    rating: 4.1,
    experience: "11 years",
    fee: "1800 NPR",
    bio: "Dr. Suman Koirala is a cardiologist with a focus on preventive heart care and minimally invasive treatments.",
  },
  {
    id: 8,
    img: doctor2,
    name: "Dr. Roshani Lama",
    specializedIn: "Neurologist",
    status: true,
    rating: 3.8,
    experience: "5 years",
    fee: "1000 NPR",
    bio: "Dr. Roshani Lama specializes in neurological disorders and is dedicated to providing patient-centered care with modern treatment methods.",
  },
  {
    id: 9,
    img: doctor1,
    name: "Dr. Dipesh Shrestha",
    specializedIn: "General Physician",
    status: true,
    rating: 4.4,
    experience: "6 years",
    fee: "900 NPR",
    bio: "Dr. Dipesh Shrestha is a general physician passionate about preventive medicine and ensuring long-term wellness for his patients.",
  },
  {
    id: 10,
    img: doctor2,
    name: "Dr. Nisha Karki",
    specializedIn: "Dermatologist",
    status: true,
    rating: 4.6,
    experience: "13 years",
    fee: "1600 NPR",
    bio: "Dr. Nisha Karki is an expert dermatologist helping patients achieve healthy and glowing skin with advanced treatments.",
  },
  {
    id: 11,
    img: doctor1,
    name: "Dr. Aarav Joshi",
    specializedIn: "Pediatrician",
    status: true,
    rating: 4.1,
    experience: "7 years",
    fee: "1000 NPR",
    bio: "Dr. Aarav Joshi is a pediatrician committed to children’s growth and preventive health care.",
  },
  {
    id: 12,
    img: doctor2,
    name: "Dr. Sneha Basnet",
    specializedIn: "Gynecologist",
    status: false,
    rating: 4.0,
    experience: "6 years",
    fee: "1300 NPR",
    bio: "Dr. Sneha Basnet provides expert gynecological care with a focus on reproductive health and maternal well-being.",
  },
  {
    id: 13,
    img: doctor1,
    name: "Dr. Milan Shah",
    specializedIn: "Cardiologist",
    status: true,
    rating: 4.7,
    experience: "14 years",
    fee: "1900 NPR",
    bio: "Dr. Milan Shah is a senior cardiologist specializing in preventive and interventional cardiology.",
  },
  {
    id: 14,
    img: doctor2,
    name: "Dr. Kritika Kharel",
    specializedIn: "Neurologist",
    status: true,
    rating: 4.3,
    experience: "9 years",
    fee: "1400 NPR",
    bio: "Dr. Kritika Kharel focuses on treating neurological conditions with a patient-first approach.",
  },
  {
    id: 15,
    img: doctor1,
    name: "Dr. Roshan Bhandari",
    specializedIn: "General Physician",
    status: false,
    rating: 3.9,
    experience: "5 years",
    fee: "750 NPR",
    bio: "Dr. Roshan Bhandari offers general health consultations and preventive care services.",
  },
  {
    id: 16,
    img: doctor2,
    name: "Dr. Priya Maharjan",
    specializedIn: "Dermatologist",
    status: true,
    rating: 4.2,
    experience: "8 years",
    fee: "1200 NPR",
    bio: "Dr. Priya Maharjan is a dermatologist experienced in skincare and aesthetic treatments.",
  },
  {
    id: 17,
    img: doctor1,
    name: "Dr. Rahul Shrestha",
    specializedIn: "Neurologist",
    status: false,
    rating: 3.7,
    experience: "4 years",
    fee: "950 NPR",
    bio: "Dr. Rahul Shrestha treats neurological conditions with a modern and evidence-based approach.",
  },
  {
    id: 18,
    img: doctor2,
    name: "Dr. Maya Rijal",
    specializedIn: "Gynecologist",
    status: true,
    rating: 4.5,
    experience: "12 years",
    fee: "1500 NPR",
    bio: "Dr. Maya Rijal provides expert care in gynecology, infertility treatment, and prenatal care.",
  },
  {
    id: 19,
    img: doctor1,
    name: "Dr. Bikash Ghimire",
    specializedIn: "General Physician",
    status: true,
    rating: 4.0,
    experience: "7 years",
    fee: "850 NPR",
    bio: "Dr. Bikash Ghimire provides holistic treatment for common illnesses and preventive health advice.",
  },
  {
    id: 20,
    img: doctor2,
    name: "Dr. Anita Thapa",
    specializedIn: "Cardiologist",
    status: true,
    rating: 4.6,
    experience: "10 years",
    fee: "1750 NPR",
    bio: "Dr. Anita Thapa is a cardiologist passionate about preventive care and lifestyle-based heart health solutions.",
  },
];
